import streamlit as st
import json
import os
from datetime import datetime
import pandas as pd

st.set_page_config(layout="wide")
st.title("📡 Realtime Telemetry (Manual Update + Logging)")

# -------------------------------------------------------------------
# Correct relative paths based on your directory structure
# -------------------------------------------------------------------
# Streamlit file is inside: streamlit_app/pages/
# So we go ONE LEVEL UP to reach /data/
DATA_FILE = os.path.join("data", "realtime.json")
LOG_DIR = os.path.join("data", "logs")

os.makedirs(LOG_DIR, exist_ok=True)

# -------------------------------------------------------------------
# Initialize session state
# -------------------------------------------------------------------
if "history" not in st.session_state:
    st.session_state.history = {
        "coolant": [],
        "speed": [],
        "brake": [],
        "yaw": []
    }

if "log_file" not in st.session_state:
    st.session_state.log_file = None  # No active session yet

# -------------------------------------------------------------------
# Create a new session log file
# -------------------------------------------------------------------
def start_new_session():
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"session_{timestamp}.json"
    filepath = os.path.join(LOG_DIR, filename)

    # Initialize empty JSON list
    with open(filepath, "w") as f:
        json.dump([], f, indent=2)

    st.session_state.log_file = filepath
    st.success(f"Started new session log: {filename}")


# -------------------------------------------------------------------
# Append one telemetry sample to the log file
# -------------------------------------------------------------------
def append_to_log(sample):
    log_file = st.session_state.log_file
    if log_file is None:
        st.error("⚠️ No active session. Click 'Start New Session' first.")
        return

    try:
        with open(log_file, "r") as f:
            content = json.load(f)
    except:
        content = []

    content.append(sample)

    with open(log_file, "w") as f:
        json.dump(content, f, indent=2)


# -------------------------------------------------------------------
# UI Controls
# -------------------------------------------------------------------
colA, colB = st.columns(2)

if colA.button("🆕 Start New Session"):
    start_new_session()

update_btn = colB.button("🔄 Update Telemetry")

placeholder = st.empty()

# -------------------------------------------------------------------
# Manual data update
# -------------------------------------------------------------------
if update_btn:

    # --- Load realtime.json (generated by simulator) ---
    if not os.path.exists(DATA_FILE):
        st.error(f"Realtime source not found: {DATA_FILE}")
        st.stop()

    try:
        with open(DATA_FILE, "r") as f:
            data = json.load(f)
    except Exception as e:
        st.error(f"Failed to read realtime JSON: {e}")
        st.stop()

    # --- Build telemetry sample ---
    sample = {
        "timestamp": data.get("timestamp", float(datetime.now().timestamp())),
        "coolant_temp": data["coolant_temp"],
        "wheel_speed": data["wheel_speed"],
        "brake_pressure": data["brake_pressure"],
        "imu": {
            "ax": data["imu"]["ax"],
            "ay": data["imu"]["ay"],
            "yaw": data["imu"]["yaw"]
        }
    }

    # --- Append to session log ---
    append_to_log(sample)

    # --- Update client-side rolling history ---
    hist = st.session_state.history
    hist["coolant"].append(sample["coolant_temp"])
    hist["speed"].append(sample["wheel_speed"])
    hist["brake"].append(sample["brake_pressure"])
    hist["yaw"].append(sample["imu"]["yaw"])

    # Keep last 200 samples
    for k in hist:
        hist[k] = hist[k][-200:]

    # Rolling chart dataframe
    df = pd.DataFrame({
        "Coolant Temp (°C)": hist["coolant"],
        "Wheel Speed (km/h)": hist["speed"],
        "Brake Pressure (bar)": hist["brake"],
        "Yaw (deg)": hist["yaw"]
    })

    # --- Render UI ---
    with placeholder.container():
        st.subheader("📡 Latest Telemetry Sample")

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Coolant Temp (°C)", sample["coolant_temp"])
        c2.metric("Wheel Speed (km/h)", sample["wheel_speed"])
        c3.metric("Brake Pressure (bar)", sample["brake_pressure"])
        c4.metric("Yaw (deg)", round(sample["imu"]["yaw"], 3))

        st.subheader("📈 Live Rolling Chart")
        st.line_chart(df)

else:
    st.info("Click **Update Telemetry** to read new data.\nClick **Start New Session** to begin logging.")


# import streamlit as st
# import json
# import os
# from datetime import datetime
# import pandas as pd

# st.set_page_config(layout="wide")
# st.title("📡 Realtime Telemetry (Manual Update + Logging)")

# # Paths
# DATA_FILE = os.path.join("data", "realtime.json")
# LOG_DIR = os.path.join("data", "logs")

# os.makedirs(LOG_DIR, exist_ok=True)

# # --------------------------------------------------------
# # Initialize session state
# # --------------------------------------------------------
# if "history" not in st.session_state:
#     st.session_state.history = {
#         "coolant": [],
#         "speed": [],
#         "brake": [],
#         "yaw": []
#     }

# if "log_file" not in st.session_state:
#     st.session_state.log_file = None  # No active session yet

# # --------------------------------------------------------
# # Create a new log session
# # --------------------------------------------------------
# def start_new_session():
#     timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
#     filename = f"session_{timestamp}.json"
#     filepath = os.path.join(LOG_DIR, filename)

#     # create an empty JSON list
#     with open(filepath, "w") as f:
#         json.dump([], f, indent=2)

#     st.session_state.log_file = filepath
#     st.success(f"Started new session: {filename}")


# # --------------------------------------------------------
# # Append a new telemetry sample to the current log
# # --------------------------------------------------------
# def append_to_log(sample):
#     if not st.session_state.log_file:
#         st.error("No active telemetry session. Click 'Start New Session' first.")
#         return

#     try:
#         with open(st.session_state.log_file, "r") as f:
#             logs = json.load(f)
#     except:
#         logs = []

#     logs.append(sample)

#     with open(st.session_state.log_file, "w") as f:
#         json.dump(logs, f, indent=2)


# # --------------------------------------------------------
# # UI Buttons
# # --------------------------------------------------------
# colA, colB = st.columns(2)

# if colA.button("🆕 Start New Session"):
#     start_new_session()

# update_button = colB.button("🔄 Update Telemetry")

# placeholder = st.empty()

# # --------------------------------------------------------
# # Handle telemetry update button
# # --------------------------------------------------------
# if update_button:

#     if not os.path.exists(DATA_FILE):
#         st.error(f"Realtime data file not found: {DATA_FILE}")
#         st.stop()

#     # Load realtime telemetry source
#     try:
#         with open(DATA_FILE, "r") as f:
#             data = json.load(f)
#     except:
#         st.error("Failed to read realtime telemetry JSON.")
#         st.stop()

#     sample = {
#         "timestamp": data["timestamp"] if "timestamp" in data else float(datetime.now().timestamp()),
#         "coolant_temp": data["coolant_temp"],
#         "wheel_speed": data["wheel_speed"],
#         "brake_pressure": data["brake_pressure"],
#         "imu": {
#             "ax": data["imu"]["ax"],
#             "ay": data["imu"]["ay"],
#             "yaw": data["imu"]["yaw"]
#         }
#     }

#     # append sample to log
#     append_to_log(sample)

#     # update UI history buffer
#     hist = st.session_state.history
#     hist["coolant"].append(sample["coolant_temp"])
#     hist["speed"].append(sample["wheel_speed"])
#     hist["brake"].append(sample["brake_pressure"])
#     hist["yaw"].append(sample["imu"]["yaw"])

#     # keep last 200 points for plotting
#     for k in hist:
#         hist[k] = hist[k][-200:]

#     # dataframe for chart
#     df = pd.DataFrame({
#         "Coolant Temp (°C)": hist["coolant"],
#         "Wheel Speed (km/h)": hist["speed"],
#         "Brake Pressure (bar)": hist["brake"],
#         "Yaw (deg)": hist["yaw"]
#     })

#     # --------------------------------------------------------
#     # Render dashboard
#     # --------------------------------------------------------
#     with placeholder.container():
#         st.subheader("📡 Telemetry Snapshot")

#         c1, c2, c3, c4 = st.columns(4)
#         c1.metric("Coolant Temp (°C)", sample["coolant_temp"])
#         c2.metric("Wheel Speed (km/h)", sample["wheel_speed"])
#         c3.metric("Brake Pressure (bar)", sample["brake_pressure"])
#         c4.metric("Yaw (deg)", round(sample["imu"]["yaw"], 3))

#         st.subheader("📈 Live Rolling Chart")
#         st.line_chart(df)

# else:
#     st.info("Click **Update Telemetry** to fetch new data.\nClick **Start New Session** to begin logging.")


# import streamlit as st
# import json
# import time

# st.title("📡 Realtime Telemetry")

# placeholder = st.empty()

# while True:
#     with open("data/realtime.json", "r") as f:
#         data = json.load(f)

#     with placeholder.container():
#         st.write(data)

#     time.sleep(0.1)
